#**Pandas**
* Data analysis and data handling
  * Read data
  * Clean data
  * Statistics of data
* It is built on top of NumPy
---
**Main data structures**
* Series: array with labeled index
* Dataframe: matrix with labeled index and columns

##Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.random.randint(5, 50, 3)
arr

array([49, 17, 28])

In [4]:
series = pd.Series(arr)
series

0    49
1    17
2    28
dtype: int64

In [5]:
labels = ['a', 'b', 'c']
series = pd.Series(arr, labels)
series

a    49
b    17
c    28
dtype: int64

In [6]:
series['a']

49

In [7]:
states = ['CE', 'RN', 'PI', 'MA']
sales_per_state1 = np.random.randint(100, 500, 4)
sales_per_state1

array([335, 393, 369, 472])

In [8]:
sales_per_state2 = np.random.randint(100, 500, 4)
sales_per_state2

array([488, 427, 443, 222])

In [9]:
series_sales1 = pd.Series(sales_per_state1, states)
series_sales1

CE    335
RN    393
PI    369
MA    472
dtype: int64

In [10]:
series_sales2 = pd.Series(sales_per_state2, states)
series_sales2

CE    488
RN    427
PI    443
MA    222
dtype: int64

In [11]:
series_sales1['MA']

472

In [12]:
series_sales2[1]

427

In [13]:
series_sales1 + series_sales2

CE    823
RN    820
PI    812
MA    694
dtype: int64

In [14]:
dic = {'CE': 100, 'RN': 150, 'MA': 120}
dic

{'CE': 100, 'MA': 120, 'RN': 150}

In [15]:
series = pd.Series(dic)
series

CE    100
RN    150
MA    120
dtype: int64

##Dataframes

In [16]:
columns = ['W', 'X', 'Y', 'Z']
index = ['A', 'B', 'C']

arr = np.random.randint(-100, 100, (3, 4))
arr

array([[-38,  -3,  81,  16],
       [ -5,  48, -29,   0],
       [ -9,  98,  71, -83]])

In [17]:
data_frame1 = pd.DataFrame(arr, index, columns)
data_frame1

W   X   Y   Z
A -38  -3  81  16
B  -5  48 -29   0
C  -9  98  71 -83

In [18]:
type(data_frame1)

pandas.core.frame.DataFrame

In [19]:
data_frame1['X']

A    -3
B    48
C    98
Name: X, dtype: int64

In [20]:
type(data_frame1['X'])

pandas.core.series.Series

In [21]:
data_frame1[['Y', 'W']]

Y   W
A  81 -38
B -29  -5
C  71  -9

In [22]:
data_frame1.describe()

W          X          Y          Z
count   3.000000   3.000000   3.000000   3.000000
mean  -17.333333  47.666667  41.000000 -22.333333
std    18.009257  50.500825  60.827625  53.144457
min   -38.000000  -3.000000 -29.000000 -83.000000
25%   -23.500000  22.500000  21.000000 -41.500000
50%    -9.000000  48.000000  71.000000   0.000000
75%    -7.000000  73.000000  76.000000   8.000000
max    -5.000000  98.000000  81.000000  16.000000

In [24]:
data_frame1['V'] = data_frame1['X'] + data_frame1['Z']
data_frame1

W   X   Y   Z   V
A -38  -3  81  16  13
B  -5  48 -29   0  48
C  -9  98  71 -83  15

In [25]:
data_frame1.columns

Index(['W', 'X', 'Y', 'Z', 'V'], dtype='object')

In [26]:
data_frame1.index

Index(['A', 'B', 'C'], dtype='object')

In [27]:
data_frame1.drop('B')

W   X   Y   Z   V
A -38  -3  81  16  13
C  -9  98  71 -83  15

In [28]:
data_frame1

W   X   Y   Z   V
A -38  -3  81  16  13
B  -5  48 -29   0  48
C  -9  98  71 -83  15

In [30]:
data_frame1.drop('W', axis=1)

X   Y   Z   V
A  -3  81  16  13
B  48 -29   0  48
C  98  71 -83  15

In [31]:
data_frame1.shape

(3, 5)

In [33]:
data_frame1

W   X   Y   Z   V
A -38  -3  81  16  13
B  -5  48 -29   0  48
C  -9  98  71 -83  15

In [32]:
data_frame1.loc['A']   # localization

W   -38
X    -3
Y    81
Z    16
V    13
Name: A, dtype: int64

In [34]:
data_frame1.loc[['C', 'A']]

W   X   Y   Z   V
C  -9  98  71 -83  15
A -38  -3  81  16  13

In [35]:
data_frame1.iloc[1]

W    -5
X    48
Y   -29
Z     0
V    48
Name: B, dtype: int64

In [36]:
data_frame1.iloc[1, 2]

-29

In [37]:
data_frame1.loc[['C', 'A'], ['V', 'X']]

V   X
C  15  98
A  13  -3

In [39]:
data_frame1['X']

A    -3
B    48
C    98
Name: X, dtype: int64

In [40]:
data_frame1['X'] > 0

A    False
B     True
C     True
Name: X, dtype: bool

In [41]:
data_frame1[data_frame1['X'] > 0]

W   X   Y   Z   V
B -5  48 -29   0  48
C -9  98  71 -83  15

In [42]:
data_frame1[data_frame1['X'] > 0]['W']

B   -5
C   -9
Name: W, dtype: int64

In [43]:
data_frame1[data_frame1['X'] > 0][['W', 'V']]

W   V
B -5  48
C -9  15

In [47]:
data_frame1['W']['A']

-38

In [48]:
data_frame1

W   X   Y   Z   V
A -38  -3  81  16  13
B  -5  48 -29   0  48
C  -9  98  71 -83  15

In [53]:
(data_frame1['X'] > 0) & (data_frame1['V'] > 0)

A    False
B     True
C     True
dtype: bool

In [55]:
data_frame1[(data_frame1['X'] > 0) & (data_frame1['V'] > 0)]

W   X   Y   Z   V
B -5  48 -29   0  48
C -9  98  71 -83  15

In [54]:
(data_frame1['X'] > 0) | (data_frame1['V'] > 0)

A    True
B    True
C    True
dtype: bool

In [56]:
data_frame1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       3 non-null      int64
 1   X       3 non-null      int64
 2   Y       3 non-null      int64
 3   Z       3 non-null      int64
 4   V       3 non-null      int64
dtypes: int64(5)
memory usage: 224.0+ bytes


##Data Input

In [57]:
ls

drive/  sample_data/


In [58]:
cd ..

/


In [59]:
ls

bin/      dev/   lib32/  opt/   sbin/   tensorflow-1.15.2/  var/
boot/     etc/   lib64/  proc/  srv/    tmp/
content/  home/  media/  root/  swift/  tools/
datalab/  lib/   mnt/    run/   sys/    usr/


In [60]:
cd /content

/content


In [61]:
ls

drive/  sample_data/


In [62]:
data_bank = pd.read_csv('/content/drive/MyDrive/IFCE - Huawei Academy/dataset_bank.csv')
data_bank

age            job  marital  education  ... pdays  previous poutcome   y
0      30     unemployed  married    primary  ...    -1         0  unknown  no
1      33       services  married  secondary  ...   339         4  failure  no
2      35     management   single   tertiary  ...   330         1  failure  no
3      30     management  married   tertiary  ...    -1         0  unknown  no
4      59    blue-collar  married  secondary  ...    -1         0  unknown  no
...   ...            ...      ...        ...  ...   ...       ...      ...  ..
4516   33       services  married  secondary  ...    -1         0  unknown  no
4517   57  self-employed  married   tertiary  ...    -1         0  unknown  no
4518   57     technician  married  secondary  ...    -1         0  unknown  no
4519   28    blue-collar  married  secondary  ...   211         3    other  no
4520   44   entrepreneur   single   tertiary  ...   249         7    other  no

[4521 rows x 17 columns]

**Data Set Information**: https://archive.ics.uci.edu/ml/datasets/bank+marketing

In [63]:
data_bank.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [64]:
data_bank.head(2)

age         job  marital  education  ... pdays  previous poutcome   y
0   30  unemployed  married    primary  ...    -1         0  unknown  no
1   33    services  married  secondary  ...   339         4  failure  no

[2 rows x 17 columns]

In [65]:
data_bank.tail()

age            job  marital  education  ... pdays  previous poutcome   y
4516   33       services  married  secondary  ...    -1         0  unknown  no
4517   57  self-employed  married   tertiary  ...    -1         0  unknown  no
4518   57     technician  married  secondary  ...    -1         0  unknown  no
4519   28    blue-collar  married  secondary  ...   211         3    other  no
4520   44   entrepreneur   single   tertiary  ...   249         7    other  no

[5 rows x 17 columns]

In [66]:
data_bank['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [67]:
data_bank['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

In [68]:
data_bank['job'].nunique()

12

In [70]:
data_bank[data_bank['job']=='student']

age      job  marital  education  ... pdays  previous poutcome    y
13     20  student   single  secondary  ...    -1         0  unknown  yes
110    21  student   single  secondary  ...   169         3  success  yes
114    25  student   single  secondary  ...    -1         0  unknown  yes
194    23  student   single  secondary  ...    -1         0  unknown   no
234    30  student   single  secondary  ...    -1         0  unknown   no
...   ...      ...      ...        ...  ...   ...       ...      ...  ...
4214   36  student   single    unknown  ...    -1         0  unknown   no
4263   25  student  married   tertiary  ...    -1         0  unknown  yes
4332   27  student   single  secondary  ...   349         1    other   no
4439   28  student   single  secondary  ...    -1         0  unknown   no
4446   22  student   single  secondary  ...    -1         0  unknown   no

[84 rows x 17 columns]

In [71]:
data_bank[data_bank['job']=='student'].count()

age          84
job          84
marital      84
education    84
default      84
balance      84
housing      84
loan         84
contact      84
day          84
month        84
duration     84
campaign     84
pdays        84
previous     84
poutcome     84
y            84
dtype: int64

In [72]:
data_bank[data_bank['job']=='student'].shape

(84, 17)

In [73]:
data_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


In [74]:
data_bank.groupby('education').mean()

age      balance        day  ...  campaign      pdays  previous
education                                     ...                               
primary    46.833333  1411.544248  15.505900  ...  2.865782  35.069322  0.460177
secondary  40.062446  1196.814397  15.977884  ...  2.734172  40.934085  0.528621
tertiary   39.645926  1775.423704  16.009630  ...  2.901481  39.824444  0.612593
unknown    45.299465  1701.245989  15.946524  ...  2.486631  41.983957  0.508021

[4 rows x 7 columns]

In [75]:
data_bank.groupby('education').mean().loc['tertiary']

age           39.645926
balance     1775.423704
day           16.009630
duration     256.881481
campaign       2.901481
pdays         39.824444
previous       0.612593
Name: tertiary, dtype: float64

In [77]:
data_bank.groupby('education').mean().sort_values('balance')

age      balance        day  ...  campaign      pdays  previous
education                                     ...                               
secondary  40.062446  1196.814397  15.977884  ...  2.734172  40.934085  0.528621
primary    46.833333  1411.544248  15.505900  ...  2.865782  35.069322  0.460177
unknown    45.299465  1701.245989  15.946524  ...  2.486631  41.983957  0.508021
tertiary   39.645926  1775.423704  16.009630  ...  2.901481  39.824444  0.612593

[4 rows x 7 columns]

In [78]:
data_bank.groupby('education').mean().sort_values('balance', ascending=False)

age      balance        day  ...  campaign      pdays  previous
education                                     ...                               
tertiary   39.645926  1775.423704  16.009630  ...  2.901481  39.824444  0.612593
unknown    45.299465  1701.245989  15.946524  ...  2.486631  41.983957  0.508021
primary    46.833333  1411.544248  15.505900  ...  2.865782  35.069322  0.460177
secondary  40.062446  1196.814397  15.977884  ...  2.734172  40.934085  0.528621

[4 rows x 7 columns]

In [79]:
data_bank.groupby('education').mean().sort_values('balance', ascending=False).sort_values('age')

age      balance        day  ...  campaign      pdays  previous
education                                     ...                               
tertiary   39.645926  1775.423704  16.009630  ...  2.901481  39.824444  0.612593
secondary  40.062446  1196.814397  15.977884  ...  2.734172  40.934085  0.528621
unknown    45.299465  1701.245989  15.946524  ...  2.486631  41.983957  0.508021
primary    46.833333  1411.544248  15.505900  ...  2.865782  35.069322  0.460177

[4 rows x 7 columns]

In [80]:
data_bank.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [81]:
data_bank.groupby(['education', 'marital']).mean()

age      balance  ...      pdays  previous
education marital                           ...                     
primary   divorced  51.392405  1072.721519  ...  33.987342  0.417722
          married   47.511407  1371.638783  ...  35.351711  0.484791
          single    37.013699  2065.753425  ...  34.205479  0.328767
secondary divorced  43.496296   891.181481  ...  37.914815  0.422222
          married   42.404345  1272.911002  ...  39.652418  0.517870
          single    33.052545  1154.008210  ...  45.275862  0.600985
tertiary  divorced  45.148387  1437.896774  ...  42.122581  0.509677
          married   41.777166  1860.719395  ...  36.764787  0.555708
          single    34.512821  1754.711538  ...  43.816239  0.735043
unknown   divorced  50.375000  1849.333333  ...  43.750000  0.250000
          married   48.444444  1725.547009  ...  48.589744  0.461538
          single    34.652174  1562.173913  ...  24.260870  0.760870

[12 rows x 7 columns]

#One Hot Encoding

In [82]:
data_bank.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [83]:
data_bank['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [84]:
pd.get_dummies(data_bank['marital'])

divorced  married  single
0            0        1       0
1            0        1       0
2            0        0       1
3            0        1       0
4            0        1       0
...        ...      ...     ...
4516         0        1       0
4517         0        1       0
4518         0        1       0
4519         0        1       0
4520         0        0       1

[4521 rows x 3 columns]

In [86]:
data2 = pd.concat([data_bank, pd.get_dummies(data_bank['marital'])], axis=1)
data2

age            job  marital  education  ...   y  divorced married single
0      30     unemployed  married    primary  ...  no         0       1      0
1      33       services  married  secondary  ...  no         0       1      0
2      35     management   single   tertiary  ...  no         0       0      1
3      30     management  married   tertiary  ...  no         0       1      0
4      59    blue-collar  married  secondary  ...  no         0       1      0
...   ...            ...      ...        ...  ...  ..       ...     ...    ...
4516   33       services  married  secondary  ...  no         0       1      0
4517   57  self-employed  married   tertiary  ...  no         0       1      0
4518   57     technician  married  secondary  ...  no         0       1      0
4519   28    blue-collar  married  secondary  ...  no         0       1      0
4520   44   entrepreneur   single   tertiary  ...  no         0       0      1

[4521 rows x 20 columns]

In [88]:
data2.drop('marital', axis=1)

age            job  education default  ...   y divorced married single
0      30     unemployed    primary      no  ...  no        0       1      0
1      33       services  secondary      no  ...  no        0       1      0
2      35     management   tertiary      no  ...  no        0       0      1
3      30     management   tertiary      no  ...  no        0       1      0
4      59    blue-collar  secondary      no  ...  no        0       1      0
...   ...            ...        ...     ...  ...  ..      ...     ...    ...
4516   33       services  secondary      no  ...  no        0       1      0
4517   57  self-employed   tertiary     yes  ...  no        0       1      0
4518   57     technician  secondary      no  ...  no        0       1      0
4519   28    blue-collar  secondary      no  ...  no        0       1      0
4520   44   entrepreneur   tertiary      no  ...  no        0       0      1

[4521 rows x 19 columns]

In [91]:
data_bank.sort_values(['age', 'balance'], ascending=[False, False])

age      job   marital  education  ... pdays  previous poutcome    y
3311   87  retired   married    primary  ...    -1         0  unknown  yes
1866   86  retired   married  secondary  ...   101         1    other   no
4108   84  retired  divorced    primary  ...    -1         0  unknown  yes
4388   83  retired  divorced    primary  ...    -1         0  unknown  yes
1349   83  retired   married    primary  ...   140         1  failure  yes
...   ...      ...       ...        ...  ...   ...       ...      ...  ...
999    20  student    single  secondary  ...   371         5  failure   no
3233   19  student    single    unknown  ...    -1         0  unknown   no
2780   19  student    single  secondary  ...    -1         0  unknown  yes
503    19  student    single    primary  ...    -1         0  unknown  yes
1900   19  student    single    unknown  ...    -1         0  unknown   no

[4521 rows x 17 columns]